### ISSUE TITLE
Error checking in concat_gzipped

### ISSUE THREAD

**Issue by evanfields** [naobservatory/mgs-workflow#45]
When there's only one library file per sample (but not when there are several), concat_gzip includes an error checking [step](https://github.com/naobservatory/mgs-workflow/blob/master/modules/local/concatGzipped/main.nf#L48-L50): copied files are compared to the original files to make sure they're byte-for-byte identical.

Is this error checking important? `cp file1 file2` seems like a pretty safe operation; are we thinking the files are so big a random bit flip might occur?

I believe this is a pretty slow operation. Running the concat_gzipped step on a single pair of forward read + reverse read, each about 7 gigabytes, took about 22 minutes. I'm not sure how to drill down to see what part of the process took most of that time, but since the other steps should be just
* downloading reads from S3; since I ran on Batch this should be within-datacenter and very fast
* copying a file locally

I don't see where else the time could have gone.

**Comment by willbradshaw** [comment]
Thanks Evan. I added this a while ago because I was getting weird file
truncation errors that were breaking my pipeline. I think this was in the
pre-Batch era, though, so we could try disabling it and seeing if anything
horrible happens.

To be honest I want to eliminate the CONCAT_GZIPPED step altogether fairly
soon, it's an artefact of a former age that doesn't really make sense given
the new structure of the pipeline. That will require changing the structure
of the samplesheet, though.

**Comment by willbradshaw** [comment]
Subsumed within https://github.com/naobservatory/mgs-workflow/issues/49.
